version: '3'
services:
  database:
    image: "mongo"
    ports:
     - "27017:27017"
    #  for SQL it is 3306
  databaseseed:
    build: ./dataGenerator/
    depends_on:
      - database
    links:
      - database
  backend:
    build: ./server/
    ports:
      - "6200:6200"
    depends_on:
      - database
